TLF-321-changes-notify
UKHomeOffice/landlords-checking-service pull request #45
Opened 2024-09-03 15:12 UTC by RobertMcCann

Relates [TLF-321](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-321)
## What? 
Add keys to capture tenant/rental address for business email
## Why? 
## How? 
## Testing?
## Screenshots (optional)
## Anything Else? (optional)
## Check list

- [ ] I have reviewed my own pull request
- [ ] I have written tests (if relevant)

2024-09-03 16:16 UTC, dk4g commented on apps/lcs/behaviours/send-email-notification.js
> +    prospective_rental_postcode: req.sessionModel.get('valuesEnriched').tenantType === 'Prospective tenant' ?
use boolean variable`isCurrentTenant` instead

2024-09-04 16:44 UTC, jamiecarterHO requested changes
Just some of the conditional stuff on tenantType could be a little neater here. The `full_address` will probably not match the designs for format, but seems more sensible to deal with them alongside the other address aggregation code from the higher PR

2024-09-04 16:44 UTC, jamiecarterHO commented on apps/lcs/behaviours/send-email-notification.js
> +      req.sessionModel.get('tenant-postcode') : '',
you could use `req.sessionModel.get('isCurrentTenant')` as the condition here too.

2024-09-04 16:44 UTC, jamiecarterHO commented on apps/lcs/behaviours/send-email-notification.js
> +      req.sessionModel.get('tenantAddress').join('\n') : '',
Should be joined with `(', ')` to match the figma format. Same for the `full_address` param above. Also not certain this copes with optional fields address line 2 and county too well. However, I think that can be dealt with in the PR for TLF-117

2024-09-05 15:15 UTC, jamiecarterHO approved these changes
lgtm

2024-09-05 16:10 UTC, merged